-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [jxl]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace jxl

/- [jxl::bit_reader::BitReader]
   Source: 'jxl/src/bit_reader.rs', lines 13:0-19:1 -/
structure bit_reader.BitReader where
  data : Slice Std.U8
  bit_buf : Std.U64
  bits_in_buf : Std.Usize
  total_bits_read : Std.Usize
  initial_bits : Std.Usize

/- [jxl::entropy_coding::ans::Bucket]
   Source: 'jxl/src/entropy_coding/ans.rs', lines 33:0-39:1 -/
structure entropy_coding.ans.Bucket where
  alias_symbol : Std.U8
  alias_cutoff : Std.U8
  dist : Std.U16
  alias_offset : Std.U16
  alias_dist_xor : Std.U16

/- [jxl::entropy_coding::ans::AnsHistogram]
   Source: 'jxl/src/entropy_coding/ans.rs', lines 17:0-28:1 -/
structure entropy_coding.ans.AnsHistogram where
  buckets : alloc.vec.Vec entropy_coding.ans.Bucket
  log_bucket_size : Std.Usize
  bucket_mask : Std.U32
  single_symbol : Option Std.U32

/- [jxl::entropy_coding::ans::AnsCodes]
   Source: 'jxl/src/entropy_coding/ans.rs', lines 403:0-405:1 -/
structure entropy_coding.ans.AnsCodes where
  histograms : alloc.vec.Vec entropy_coding.ans.AnsHistogram

/- [jxl::entropy_coding::ans::AnsReader]
   Source: 'jxl/src/entropy_coding/ans.rs', lines 421:0-421:26 -/
@[reducible]
def entropy_coding.ans.AnsReader := Std.U32

end jxl
