-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [jxl]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import lean.Types
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
open jxl

/- [byteorder::{byteorder::ByteOrder for byteorder::LittleEndian}::read_u64]:
   Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/byteorder-1.5.0/src/lib.rs', lines 2138:4-2138:34
   Name pattern: [byteorder::{byteorder::ByteOrder<byteorder::LittleEndian>}::read_u64] -/
@[rust_fun
  "byteorder::{byteorder::ByteOrder<byteorder::LittleEndian>}::read_u64"]
axiom byteorder.ByteOrderLittleEndian.read_u64
  : Slice Std.U8 → Result Std.U64

